using System.Text.Json.Serialization;
using Vapi.Net.Core;

#nullable enable

namespace Vapi.Net;

public record Payment
{
    /// <summary>
    /// This is the id of the payment
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; set; }

    /// <summary>
    /// This is the id of the org
    /// </summary>
    [JsonPropertyName("orgId")]
    public string? OrgId { get; set; }

    /// <summary>
    /// This is the total cost of the payment, which is the sum of all the costs in the costs object.
    ///
    /// Note: this is a string to avoid floating point precision issues.
    /// </summary>
    [JsonPropertyName("cost")]
    public required string Cost { get; set; }

    /// <summary>
    /// This is the itemized breakdown of payment amounts
    /// </summary>
    [JsonPropertyName("costs")]
    public IEnumerable<object> Costs { get; set; } = new List<object>();

    /// <summary>
    /// This is the status of the payment
    /// </summary>
    [JsonPropertyName("status")]
    public required PaymentStatus Status { get; set; }

    /// <summary>
    /// This is the timestamp when the payment was created
    /// </summary>
    [JsonPropertyName("createdAt")]
    public required DateTime CreatedAt { get; set; }

    /// <summary>
    /// This is the timestamp when the payment was last updated
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public required DateTime UpdatedAt { get; set; }

    /// <summary>
    /// This indicates if this payment was automatically generated by the auto-reload feature
    /// </summary>
    [JsonPropertyName("isAutoReload")]
    public required bool IsAutoReload { get; set; }

    /// <summary>
    /// This is the id of the subscription the payment belongs to
    /// </summary>
    [JsonPropertyName("subscriptionId")]
    public required string SubscriptionId { get; set; }

    /// <summary>
    /// This is the id of the call
    /// </summary>
    [JsonPropertyName("callId")]
    public string? CallId { get; set; }

    /// <summary>
    /// This is the id of the purchased phone number
    /// </summary>
    [JsonPropertyName("phoneNumberId")]
    public string? PhoneNumberId { get; set; }

    /// <summary>
    /// This is the id of the associated stripe payment intent
    /// </summary>
    [JsonPropertyName("stripePaymentIntentId")]
    public string? StripePaymentIntentId { get; set; }

    /// <summary>
    /// This is the id of the associated stripe invoice
    /// </summary>
    [JsonPropertyName("stripeInvoiceId")]
    public string? StripeInvoiceId { get; set; }

    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
